services:
  mysql:
    image: mysql:8
    container_name: mysql-8-task
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: my_mysql_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql  # 로컬 폴더 mysql_data와 컨테이너 연결